### ISSUE TITLE
Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by r2shyyou** [adhyh/homebridge-vwconnectid#10]
**Describe The Bug:**
Getting the following error(s) even after restarting:

**Logs:**

```
[16/06/2023, 09:50:42] [Car] TypeError: Cannot read properties of undefined (reading 'forEach')
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js:1354:35)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[16/06/2023, 09:50:42] [Car] TypeError: Cannot read properties of undefined (reading 'forEach')
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js:1354:35)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[16/06/2023, 09:50:42] [Car] Not able to find vehicle, did you choose the correct type?
[16/06/2023, 09:50:42] [Car] Get Vehicles Failed
```

**Environment:**

* **Plugin Version**: 1.1.2
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 18.16.0
* **NPM Version**: 9.5.1
* **Operating System**: Raspbian

**Comment by adhyh** [comment]
Hi Arthur, can you check (restart) again? Looks like there was an issue at VW side until around 10:30 am.

**Comment by r2shyyou** [comment]
just restarted again and it does look better now!
