### ISSUE TITLE
Plugin crash Volkswagen App

### ISSUE THREAD

**Issue by Libar19** [adhyh/homebridge-vwconnectid#19]
Hi  
I have a problem with the plugin, it works, but after 2-3 hours it crashes the Volkswagen app, and I have to wait around 24 hours. Here's a photo of my app when it crashes (it's only on the car tab, not the location. I also have the problem on the Volkswagen site, I can't access consumption of my vehicle during the accident. Do you have any ideas?

Log Homebridge with "BUG":

[4/20/2024, 9:44:48 PM] [We Connect ID] Error: Invalid protocol: weconnect:
    at Request.init (/usr/local/lib/node_modules/homebridge-vwconnectid/node_modules/request/request.js:458:31)
    at Redirect.onResponse (/usr/local/lib/node_modules/homebridge-vwconnectid/node_modules/request/lib/redirect.js:149:11)
    at Request.onRequestResponse (/usr/local/lib/node_modules/homebridge-vwconnectid/node_modules/request/request.js:986:22)
    at ClientRequest.emit (node:events:518:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at TLSSocket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[4/20/2024, 9:44:48 PM] [We Connect ID] Login successful
[4/20/2024, 9:44:48 PM] [We Connect ID] START getPersonalData()
[4/20/2024, 9:44:48 PM] [We Connect ID] START getVehicles
[4/20/2024, 9:44:49 PM] [We Connect ID] getVehicles: {"data":[{"vin":"WVWZZZAUZJW801122","role":"PRIMARY_USER","userRoleStatus":"ENABLED","enrollmentStatus":"COMPLETED","brandCode":"V","model":"Golf GTE","nickname":"Golf 7.5 GTE","capabilities":[],"images":{},"coUsers":[],"devicePlatform":"MBB","tags":[]}]}
[4/20/2024, 9:44:49 PM] [We Connect ID] START getIdStatus
[4/20/2024, 9:44:49 PM] [We Connect ID] END getIdStatus
[4/20/2024, 9:44:49 PM] [We Connect ID] START getIdParkingPosition
[4/20/2024, 9:44:49 PM] [We Connect ID] END getIdParkingPosition
[4/20/2024, 9:44:49 PM] [We Connect ID] Found WeCharge connection
[4/20/2024, 9:44:49 PM] [We Connect ID] Failled wall charger login
[4/20/2024, 9:44:49 PM] [We Connect ID] 429
[4/20/2024, 9:44:49 PM] [We Connect ID] get id parking position Failed
[4/20/2024, 9:44:49 PM] [We Connect ID] getIdStatus: {}
[4/20/2024, 9:44:50 PM] [We Connect ID] getData END
[4/20/2024, 9:44:50 PM] [We Connect ID] Active VIN successfully set to <WVWZZZAUZJW801122>.
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing charging accessory from cache: Charging
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing remaining range accessory from cache: Remaining km
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing climatisation accessory from cache: Climatisation
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing accessory from cache: Home
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing accessory from cache: Home
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing accessory from cache: Work
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing accessory from cache: Work
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing event motions sensor accessory from cache: Car unsafe state
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing setting switch accessory from cache: Reduced AC
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing setting switch accessory from cache: Plug Unlock
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing setting switch accessory from cache: Climatization at unlock
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing setting switch accessory from cache: Window Heating
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing setting switch accessory from cache: Front Left Zone
[4/20/2024, 9:44:50 PM] [We Connect ID] Restoring existing setting switch accessory from cache: Front Right Zone
[4/20/2024, 9:45:19 PM] [We Connect ID] START getIdStatus
[4/20/2024, 9:45:19 PM] [We Connect ID] END getIdStatus
[4/20/2024, 9:45:19 PM] [We Connect ID] START getIdParkingPosition
[4/20/2024, 9:45:19 PM] [We Connect ID] END getIdParkingPosition
[4/20/2024, 9:45:19 PM] [We Connect ID] 429
[4/20/2024, 9:45:19 PM] [We Connect ID] get id parking position Failed
[4/20/2024, 9:45:19 PM] [We Connect ID] Token Refresh started
[4/20/2024, 9:45:19 PM] [We Connect ID] Token Refresh successful
[4/20/2024, 9:45:19 PM] [We Connect ID] getIdStatus: {}
[4/20/2024, 9:45:19 PM] [We Connect ID] Current car state not (correctly) received from VW backend.
[4/20/2024, 9:45:19 PM] [We Connect ID] TypeError: Cannot read properties of undefined (reading 'data')
    at VwWeConnect.runEventEmitters (/usr/local/lib/node_modules/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js:1611:37)
    at Request._callback (/usr/local/lib/node_modules/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js:1743:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-vwconnectid/node_modules/request/request.js:185:22)
    at Request.emit (node:events:518:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-vwconnectid/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:518:28)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/homebridge-vwconnectid/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:632:28)
    at Gunzip.emit (node:events:518:28)
    at endReadableNT (node:internal/streams/readable:1696:12)
[4/20/2024, 9:45:20 PM] [We Connect ID] Found WeCharge connection
[4/20/2024, 9:45:20 PM] [We Connect ID] No able to Login in WeCharge
[4/20/2024, 9:45:49 PM] [We Connect ID] START getIdStatus
[4/20/2024, 9:45:49 PM] [We Connect ID] END getIdStatus
[4/20/2024, 9:45:49 PM] [We Connect ID] START getIdParkingPosition
[4/20/2024, 9:45:49 PM] [We Connect ID] END getIdParkingPosition
[4/20/2024, 9:45:49 PM] [We Connect ID] 429
[4/20/2024, 9:45:49 PM] [We Connect ID] get id parking position Failed
[4/20/2024, 9:45:49 PM] [We Connect ID] Token Refresh started
[4/20/2024, 9:45:49 PM] [We Connect ID] Token Refresh successful
[4/20/2024, 9:45:49 PM] [We Connect ID] getIdStatus: {}
[4/20/2024, 9:45:50 PM] [We Connect ID] Found WeCharge connection
[4/20/2024, 9:45:50 PM] [We Connect ID] No able to Login in WeCharge
[4/20/2024, 9:46:19 PM] [We Connect ID] START getIdStatus
[4/20/2024, 9:46:19 PM] [We Connect ID] END getIdStatus
[4/20/2024, 9:46:19 PM] [We Connect ID] START getIdParkingPosition
[4/20/2024, 9:46:19 PM] [We Connect ID] END getIdParkingPosition
[4/20/2024, 9:46:19 PM] [We Connect ID] 429
[4/20/2024, 9:46:19 PM] [We Connect ID] get id parking position Failed
[4/20/2024, 9:46:19 PM] [We Connect ID] Token Refresh started
[4/20/2024, 9:46:19 PM] [We Connect ID] Token Refresh successful
[4/20/2024, 9:46:20 PM] [We Connect ID] getIdStatus: {}
[4/20/2024, 9:46:20 PM] [We Connect ID] Found WeCharge connection
[4/20/2024, 9:46:20 PM] [We Connect ID] No able to Login in WeCharge

Picture of myvolkswagen
<img width="1461" alt="Capture d’écran 2024-04-20 à 21 47 30" src="https://github.com/adhyh/homebridge-vwconnectid/assets/116975798/a69582ee-a6f5-4d47-b6c1-1827d60730ff">

picture Volkswagen app for ios
![IMG_4B7CE75F8D9C-1](https://github.com/adhyh/homebridge-vwconnectid/assets/116975798/8cc38246-3ef6-4001-b62f-c7ea0769257f)

**Comment by Libar19** [comment]
I think i have too much request (error 429)

**Comment by adhyh** [comment]
Good to hear you solved it!
