### ISSUE TITLE
New error regarding motion sensor receiving object instead of boolean

### ISSUE THREAD

**Issue by r2shyyou** [adhyh/homebridge-vwconnectid#9]
**Describe The Bug:**
i keep getting this error now:

`[19/04/2023, 13:56:17] [homebridge-vwconnectid] This plugin generated a warning from the characteristic 'Motion Detected': characteristic value expected boolean and received object. See https://homebridge.io/w/JtMGR for more info.`

the two characteristics i've added since the update to 1.1.1 are as follows:

`"name": "Car is Locked",`
`"event": "locked"`
`},`
`{`
`"name": "Charging Not Working",`
`"event": "noExternalPower"`

**Environment:**

* **Plugin Version**: 1.1.1
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 18.15.0
* **NPM Version**: 9.5.0
* **Operating System**: Raspbian

**Comment by r2shyyou** [comment]
i do have a parked motion sensor, but i don't feel like that's causing an issue. i just restarted HB and have the following in the log:

```
[20/04/2023, 12:37:14] [Car] 429
[20/04/2023, 12:37:14] [Car] TypeError: Cannot read properties of undefined (reading 'forEach')
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js:1352:35)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at Gunzip.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at Gunzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[20/04/2023, 12:37:14] [Car] TypeError: Cannot read properties of undefined (reading 'forEach')
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js:1352:35)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at Gunzip.<anonymous> (/var/lib/homebridge/node_modules/homebridge-vwconnectid/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at Gunzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[20/04/2023, 12:37:14] [Car] Not able to find vehicle, did you choose the correct type?
[20/04/2023, 12:37:14] [Car] Get Vehicles Failed
[20/04/2023, 12:37:15] [Car] Failled wall charger login
```

**Comment by adhyh** [comment]
It probably is the 'parked' sensor though, looking at the code. I will take care of it in the next update.

The other error you're seeing now is an issue at VW side. It will go away eventually.

**Comment by r2shyyou** [comment]
> It probably is the 'parked' sensor though, looking at the code. I will take care of it in the next update.
> 
> 
> 
> The other error you're seeing now is an issue at VW side. It will go away eventually. 

okay, thanks, i'll be on the lookout for the next update. thanks again!

**Comment by adhyh** [comment]
I think I solved it. Let me test this a bit more, hopefully this was the only bug.

And thanks for the support - much appreciated!
